### ISSUE TITLE
BOINC can't attach to account manager

### ISSUE THREAD

**Issue by sxiii** [diy-forge/boinc-kubernetes#2]
Greetings! It's the third day of me trying to set up this repo to work in my K8S environment.

I've tried this repo along with some others and also made my own containers and deployments and nothing seems to work, so I resorted to asking here - hope this is OK.

I'm trying to connect to GRCPOOL.com account manager. Whenever I launch the deployment, I'm getting pretty standard error "boinc
15-Aug-2022 13:54:19 [---] This computer is not attached to any projects", even though I specified everything in the ENV:
```
        env:
        - name: BOINC_CMD_LINE_OPTIONS
          #value: "--acct_mgr attach https://www.grcpool.com $SECRET_USERNAME $SECRET_PASSWORD"
          value: "--join_acct_mgr https://www.grcpool.com $SECRET_USERNAME $SECRET_PASSWORD"
```
And set-up the secrets (BTW, your secret template says that there should be user's email, while it should be user login at least for GRCPOOL - don't know if this is a typo or if different pools work differently).

I've also tried different other containers and nothing really helped. If I manually try to attach the node after it started, I'm getting this:
```
root@boinc-deployment-68499f4b96-5bf5b:/# boinccmd --acct_mgr attach https://www.grcpool.com LOGIN PASSWORD
root@boinc-deployment-68499f4b96-5bf5b:/# boinccmd --acct_mgr sync
root@boinc-deployment-68499f4b96-5bf5b:/# boinccmd --acct_mgr info
Operation failed: unexpected XML tag or syntax
```
I've tried also adding port forwarding rules, load balancers and pretty everything I could think of. Could you help here a bit maybe @Pelirrojo ? Thanks!
